### ISSUE TITLE
Paraphrase cloze

### ISSUE THREAD

**Issue by aolney** [aolney/mofacts-automated-authoring#34]
- [x] Select/develop paraphrase system
- [x] Create a small number of "best" paraphrases for selected cloze such that
  - Fill in is the same across
  - Paraphrases are list nested under cloze item in json

Linked to https://github.com/memphis-iis/mofacts-ies/issues/158

See output format discussion here https://github.com/aolney/mofacts-automated-authoring/issues/16#issuecomment-669517175

**Comment by imrryr** [comment]
Doh... so this task means the stim files are not done until they have the paraphrases in them....
