### ISSUE TITLE
Make MC and T/F item variants

### ISSUE THREAD

**Issue by aolney** [aolney/mofacts-automated-authoring#38]
Use BERT to create options; might require upgrading AllenNLP

**Comment by aolney** [comment]
This would be relatively easy to do with the Macaw work from last year

**Comment by imrryr** [comment]
This is a great thing to do. Can you also make glossary-type short answer flashcards? Stimulus - One of 12 sets of cranial nerves. It enables movement in the eye's superior oblique muscle. This makes it possible to look down. The nerve also enables you to move your eyes toward your nose or away from it. Response - Trochlear nerve

**Comment by aolney** [comment]
> This is a great thing to do. Can you also make glossary-type short answer flashcards? Stimulus - One of 12 sets of cranial nerves. It enables movement in the eye's superior oblique muscle. This makes it possible to look down. The nerve also enables you to move your eyes toward your nose or away from it. Response - Trochlear nerve

Did you get this example from the text? If so, it would be good for me to look at the original page to see how it fits in the context of the chapter.

Jeff's  stuff can be used for definitions, but what you have here is pretty elaborated and goes beyond what I normally think of when I think of a glossary entry.

**Comment by aolney** [comment]
I submitted a paper to the AIED LLM workshop that shows Macaw can do this an be as good as humans if you solve the duplicated answer options issue. BingChat is also very close to humans but tends to not follow the prompt correctly.

Pragmatically, BingChat is easier to work with for this unless you have a graphics card with ~45GB of RAM or a CPU with 256GB RAM, which is what Macaw 11GB needs
