### ISSUE TITLE
Add test for parser edge case

### ISSUE THREAD

**Issue by andrewtackett** [aolney/mofacts-automated-authoring#50]
The following input seems to crash the parser:

{
                    "responseType": "image",
                    "stims": [
                        {
                            "response": {
                                "correctResponse": "images/Countries/algeria_sm_2011.gif",
                                "incorrectResponses": [
                                    "images/Countries/afghanistan_sm_2011.gif",
                                    "images/Countries/akrotiri_sm_2011.gif",
                                    "images/Countries/albania_sm_2011.gif"
                                ]
                            },
                            "display": {
                                "text":"Algeria"
                            },
                            "parameter": "-0.479299999999998"
                        }
                    ]
                }

specifically I'm betting it's the forward slashes.

**Comment by aolney** [comment]
Lost track of this and don't know why the parser would be involved here. Closing for now.
