### ISSUE TITLE
API data model

### ISSUE THREAD

**Issue by aolney** [aolney/mofacts-automated-authoring#6]
Create JSON for consumption by MoFaCTs
- [x] Create evaluation json using old process in beaker
- [x] Output conformant json as API call

Example:
```
{   sentences: [
     {"sentence":"Lorem ipsum dolor sit amet", "itemId":<some-uuid-1>,
"hasCloze":true},
     ...
   ],
   clozes: [
     {"cloze":"Lorem _____ dolor sit amet", "itemId":<some-uuid-1>,
"clozeId":<some-uuid-2>, "correctResponse":"ipsum"},
     {"cloze":"Lorem ipsum dolor sit _____", "itemId":<some-uuid-1>,
"clozeId":<some-uuid-3>, "correctResponse":"amet"},
     ...
   ]
}
```
itemId is a mapping to the underlying object whereas clozeId is unique for
each cloze. Let me know if you have any questions.

**Comment by aolney** [comment]
Sent evaluation beaker json to Grayson

**Comment by andrewtackett** [comment]
Hey Andrew, please send this and future stuff to me as Grayson's last day was yesterday.

**Comment by aolney** [comment]
done with https://github.com/aolney/mofacts-automated-authoring/commit/a144207b033fb9a88dde899d73ab21ff943b55a1
